# ============================================================================
# dofus-retro-deobfuscator — Multi-stage Docker build
#
# Stage 1 (v8-builder): Compiles V8 8.7.220.31 with bytecode disassembly patches
# Stage 2 (runtime):    Node.js + Python3 runtime with the full deobfuscation pipeline
#
# Manually clones V8 + deps from GitHub mirrors at exact pinned commits.
# ZERO requests to chromium.googlesource.com (except depot_tools).
#
# Author: Luska
# ============================================================================

# ── Stage 1: Build V8 8.7 + v8dasm ─────────────────────────────────────────
FROM ubuntu:20.04 AS v8-builder

ENV DEBIAN_FRONTEND=noninteractive
ENV PATH="/depot_tools:${PATH}"
ENV DEPOT_TOOLS_UPDATE=0

RUN apt-get update && apt-get install -y \
    git curl unzip python3 python3-pip pkg-config \
    build-essential clang lld ninja-build \
    && ln -sf /usr/bin/python3 /usr/bin/python \
    && rm -rf /var/lib/apt/lists/*

# Install depot_tools (provides gn)
RUN git clone --depth=1 https://chromium.googlesource.com/chromium/tools/depot_tools.git /depot_tools \
    && bash /depot_tools/ensure_bootstrap

# Clone V8 8.7.220.31 from GitHub mirror
WORKDIR /v8_build
RUN git init v8 && cd v8 \
    && git remote add origin https://github.com/v8/v8.git \
    && git fetch --depth=1 origin 8.7.220.31 \
    && git checkout FETCH_HEAD

# Clone essential deps at exact pinned commits from GitHub mirrors
WORKDIR /v8_build/v8
COPY clone_deps.py /tmp/clone_deps.py
RUN python3 /tmp/clone_deps.py

# Apply patches to bypass version/checksum checks and enable bytecode printing
COPY v8dasm/patch_v8.py /tmp/patch_v8.py
# Create gclient_args.gni (normally generated by gclient runhooks)
RUN mkdir -p build/config && printf 'build_with_chromium = false\ncheckout_google_benchmark = false\n' > build/config/gclient_args.gni

# Download gn binary at the exact version V8 8.7 expects (from buildtools DEPS)
RUN mkdir -p buildtools/linux64 \
    && curl -sL "https://chrome-infra-packages.appspot.com/dl/gn/gn/linux-amd64/+/git_revision:e002e68a48d1c82648eadde2f6aafa20d08c36f2" -o /tmp/gn.zip \
    && unzip -o /tmp/gn.zip -d buildtools/linux64/ \
    && chmod +x buildtools/linux64/gn \
    && rm /tmp/gn.zip

RUN python3 /tmp/patch_v8.py

# Configure and build V8 as a static monolith (no ICU, no custom libc++)
RUN mkdir -p out/Default \
    && printf 'is_debug = false\ntarget_cpu = "x64"\nv8_enable_disassembler = true\nv8_enable_object_print = true\nis_component_build = false\nv8_monolithic = true\nuse_custom_libcxx = false\nv8_use_external_startup_data = false\nv8_enable_i18n_support = false\ntreat_warnings_as_errors = false\n' > out/Default/args.gn \
    && gn gen out/Default \
    && /usr/bin/ninja -C out/Default v8_monolith -j$(nproc)

# Compile v8dasm against the monolith
COPY v8dasm/v8dasm.cc /tmp/v8dasm.cc
RUN g++ -std=c++17 -O2 \
    -DV8_COMPRESS_POINTERS -DV8_31BIT_SMIS_ON_64BIT_ARCH \
    -I include -I . \
    /tmp/v8dasm.cc \
    -o /usr/local/bin/v8dasm \
    -lv8_monolith -L out/Default/obj \
    -lm -ldl -lpthread -lz \
    && echo "v8dasm built successfully"


# ── Stage 2: Runtime ────────────────────────────────────────────────────────
FROM node:18-slim

RUN apt-get update && apt-get install -y \
    python3 curl zip \
    && rm -rf /var/lib/apt/lists/*

# Copy v8dasm binary from builder
COPY --from=v8-builder /usr/local/bin/v8dasm /usr/local/bin/v8dasm

# Install webcrack globally
RUN npm install -g webcrack@2 2>/dev/null

# Copy pipeline scripts
WORKDIR /app
COPY scripts/ /app/scripts/
RUN chmod +x /app/scripts/deobfuscate.sh

# Copy pre-captured resolution data (Ghidra analysis + runtime captures)
COPY data/ /app/data/

# Output directory (mount point)
VOLUME /output

ENTRYPOINT ["/app/scripts/deobfuscate.sh"]
CMD ["--help"]
